version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
        - postgresSA:/var/lib/postgresql/data
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  webserver:
    container_name: webserver
    image: php:7.4.3-apache
    ports:
      - "8181:80"
    volumes:
      - ./app2:/var/www/html
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - webserver
volumes:
  postgresSA: